Repository stm32-rs/stm32-rs, pull requests merged in 2023-05, with the labels that each got.

#837 add missing I2S*ext peripherals on f413
  devices/stm32f413.yaml
Labels: stm32f4

#839 Add changelog CI job
  .github/workflows/changelog.yaml
Labels: skip-changelog

#835 dma clusters & fixes
  devices/common_patches/stm32l4x2_l412.yaml
  devices/common_patches/tim/v2/l5.yaml
  devices/stm32f745.yaml
  devices/stm32f750.yaml
  devices/stm32f765.yaml
  devices/stm32f7x6.yaml
  devices/stm32g431.yaml
  devices/stm32g441.yaml
  devices/stm32g471.yaml
  devices/stm32g473.yaml
  devices/stm32g474.yaml
  devices/stm32g483.yaml
  devices/stm32g484.yaml
  devices/stm32g491.yaml
  devices/stm32g4a1.yaml
  devices/stm32h7b3.yaml
  devices/stm32l0x0.yaml
  devices/stm32l0x1.yaml
  devices/stm32l0x2.yaml
  devices/stm32l0x3.yaml
  devices/stm32l4p5.yaml
  devices/stm32l4r5.yaml
  devices/stm32l4r9.yaml
  devices/stm32l4x1.yaml
  devices/stm32l4x3.yaml
  devices/stm32l4x5.yaml
  devices/stm32l4x6.yaml
  devices/stm32l552.yaml
  devices/stm32l562.yaml
  svd/vendor/stm32l5_svd.zip
Labels: skip-changelog

#834 Apply TIM2 32-bit patch to STM32WB55
  devices/stm32wb55.yaml
Labels: stm32wb, skip-changelog

#841 Only run mmaps comparison when yamls/svds are changed
  .github/workflows/mmaps_pr.yaml
Labels: skip-changelog

#807 makehtml: improve expand_cluster ValueError
  scripts/makehtml.py
Labels: skip-changelog

#809 dead time
  devices/common_patches/tim/l4+.yaml
  devices/stm32f0x0.yaml
  peripherals/tim/tim16.yaml
  peripherals/tim/tim1_16bit.yaml
  peripherals/tim/tim1_wl.yaml
  peripherals/tim/tim_advanced.yaml
Labels: skip-changelog

#823 cargo make support
  Makefile.toml
  README.md
  svd/extract.ds
  svd/vendor/stm32_h5_svd.zip
Labels: skip-changelog

#831 prefix TIMPRE variant names with Max
  peripherals/rcc/rcc_v2_dckcfgr_timpre.yaml
Labels: breaking-change, skip-changelog

#842 CI updates
  .github/workflows/cargo-make.yaml
  .github/workflows/ci.yaml
  .github/workflows/mmaps_pr.yaml
Labels: skip-changelog

#803 Fix `PTPPPSCR` on `stm32f4` and `stm32f7`, add variants for `PTPPPSCR:PPSFREQ` on `stm32f2`, `stm32f4`, `stm32f7`
  devices/common_patches/ethernet/f4_f7.yaml
  devices/stm32f217.yaml
  devices/stm32f407.yaml
  devices/stm32f427.yaml
  devices/stm32f429.yaml
  devices/stm32f469.yaml
  devices/stm32f745.yaml
  devices/stm32f750.yaml
  devices/stm32f765.yaml
  devices/stm32f7x7.yaml
  devices/stm32f7x9.yaml
  peripherals/eth/eth_ptp_ppsfreq.yaml
Labels: stm32f2, stm32f4, stm32f7, skip-changelog

#843 Run cargo-make CI on pushes to master
  .github/workflows/cargo-make.yaml
  .github/workflows/mmaps_pr.yaml
Labels: skip-changelog

#829 set variant for `MT` field
  peripherals/rtc/rtc_common.yaml
Labels: skip-changelog

#764 L4x6 missing registers for dfsdm filter1 #760
  devices/stm32l4x6.yaml
Labels: stm32l4, skip-changelog

#783 Fixes missing CRSEN bit for L4x5 devices
  devices/stm32l4x5.yaml
Labels: stm32l4, skip-changelog

#799 `zeroToClear` for `TIMx SR UIF` field
  peripherals/tim/tim_no_opm.yaml
Labels: breaking-change, skip-changelog

#789 stm32g0[bc]1: Rename USB_DRD_FS like USB_FS
  devices/common_patches/usb/rename_USB_FS_peripheral_to_USB.yaml
  devices/stm32g0b1.yaml
  devices/stm32g0c1.yaml
Labels: breaking-change, stm32g0, skip-changelog
